---
title: "Lab 3"
author: 
  - Makayla Whitney
  - Joe Swinehart
  - Janette Avelar
  - David Fainstein
date: "2/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#loadling libraries needed for Lab 3
library(ggplot2)
library(here)
library(tidyverse)
library(lubridate)
library(waffle)
library(dplyr)
library(directlabels)
library(gghighlight)

#Importing files
imported_honey_production <- read.csv(here("data/honeyproduction.csv"))
census_regions <-  read_csv(here("data/us census bureau regions and divisions.csv"))

```

```{r making data friendly}
#Pairing down table to a more manageable amount of columns; one mutation
purifiedhoney <- imported_honey_production %>% 
  select(state, year, totalprod) %>% 
  mutate(prodsimpler = totalprod/1000)

#One column name reassignment
census_regions <- census_regions %>% 
  rename(state = `State Code`)
```


```{r visualize honey production over time}

ggplot(purifiedhoney, aes(year, prodsimpler)) +
  #inserting all lines first
  geom_line(aes(group=state),
            color = "gray80") +
  #then 3 geom_lines to highlight OR, WA, and CA
  geom_line(data = filter(purifiedhoney,
                           state == "OR"),
           color = "#60D838") +
    geom_line(data = filter(purifiedhoney,
                           state == "WA"),
           color = "#00A1FE") +
  
    geom_line(data = filter(purifiedhoney,
                           state == "CA"),
           color = "#FF634D") +
  #Adjusting Y-axis to be more conducive to viewing
  scale_y_log10()+
  #Adding in appropriate indications and annotations
  labs(title = "US Honey Production",
       subtitle = "1998-2012",
       y = "Thousands of gallons",
       x = "Year",
       caption = "The average honey bee's wings flap over 183 times per second.")+    
  annotate(geom = "point", x = 1998, y = 37350, colour = "#FF634D", size = 3) + 
  annotate(geom = "text", x = 1998.3, y = 37350, label = "CALIFORNIA", hjust = "left")+    
  annotate(geom = "point", x = 1998, y = 2955, colour = "#00A1FE", size = 3) + 
  annotate(geom = "text", x = 1998.3, y = 3500, label = "WASHINGTON", hjust = "left")+    
  annotate(geom = "point", x = 1998, y = 2250, colour = "#60D838", size = 3) + 
  annotate(geom = "text", x = 1998.3, y = 1900, label = "OREGON", hjust = "left")

```

```{r colorblind friendly #1 - Duetanomaly}

#Replication of code block above with one change: colors changed for accessibility to people with red-green colorblindness
ggplot(purifiedhoney, aes(year, prodsimpler)) +
  geom_line(aes(group=state),
            color = "gray80") +
  geom_line(data = filter(purifiedhoney,
                           state == "OR"),
           color = "#E5B33F") +
    geom_line(data = filter(purifiedhoney,
                           state == "WA"),
           color = "#8EA7E7") +
  
    geom_line(data = filter(purifiedhoney,
                           state == "CA"),
           color = "#FFE26A") +
  scale_y_log10()+
  labs(title = "US Honey Production",
       subtitle = "1998-2012",
       y = "Thousands of gallons",
       x = "Year",
       caption = "A queen bee can sting multiple times without dying.")+    
  annotate(geom = "point", x = 1998, y = 37350, colour = "#FFE26A", size = 3) + 
  annotate(geom = "text", x = 1998.3, y = 37350, label = "CALIFORNIA", hjust = "left")+    
  annotate(geom = "point", x = 1998, y = 2955, colour = "#8EA7E7", size = 3) + 
  annotate(geom = "text", x = 1998.3, y = 3500, label = "WASHINGTON", hjust = "left")+    
  annotate(geom = "point", x = 1998, y = 2250, colour = "#E5B33F", size = 3) + 
  annotate(geom = "text", x = 1998.3, y = 1900, label = "OREGON", hjust = "left")
```

```{r colorblind friendly #2 - Protanomaly}

#Replication of code block above with one change: colors changed for accessibility to people with a different type of red-green colorblindness
ggplot(purifiedhoney, aes(year, prodsimpler)) +
  geom_line(aes(group=state),
            color = "gray80") +
  geom_line(data = filter(purifiedhoney,
                           state == "OR"),
           color = "#FFD960") +
    geom_line(data = filter(purifiedhoney,
                           state == "WA"),
           color = "#A2B6EB") +
  
    geom_line(data = filter(purifiedhoney,
                           state == "CA"),
           color = "#D5A238") +
  scale_y_log10()+
  labs(title = "US Honey Production",
       subtitle = "1998-2012",
       y = "Thousands of gallons",
       x = "Year",
       caption = "A typical Bee colony consists of 30,000 to 60,000 bees.")+    
  annotate(geom = "point", x = 1998, y = 37350, colour = "#D5A238", size = 3) + 
  annotate(geom = "text", x = 1998.3, y = 37350, label = "CALIFORNIA", hjust = "left")+    
  annotate(geom = "point", x = 1998, y = 2955, colour = "#A2B6EB", size = 3) + 
  annotate(geom = "text", x = 1998.3, y = 3500, label = "WASHINGTON", hjust = "left")+    
  annotate(geom = "point", x = 1998, y = 2250, colour = "#FFD960", size = 3) + 
  annotate(geom = "text", x = 1998.3, y = 1900, label = "OREGON", hjust = "left")
```

```{r colorblind friendly #3 - Tritanomaly}

#Replication of code block above with one change: colors changed for accessibility to people with a blue-yellow colorblindness
ggplot(purifiedhoney, aes(year, prodsimpler)) +
  geom_line(aes(group=state),
            color = "gray80") +
  geom_line(data = filter(purifiedhoney,
                           state == "OR"),
           color = "#FF8F82") +
    geom_line(data = filter(purifiedhoney,
                           state == "WA"),
           color = "#00AE9C") +
  
    geom_line(data = filter(purifiedhoney,
                           state == "CA"),
           color = "#FFD0BC") +
  scale_y_log10()+
  labs(title = "US Honey Production",
       subtitle = "1998-2012",
       y = "Thousands of gallons",
       x = "Year",
       caption = "An adult worker bee's lifespan is about 45 days.")+    
  annotate(geom = "point", x = 1998, y = 37350, colour = "#FFD0BC", size = 3) + 
  annotate(geom = "text", x = 1998.3, y = 37350, label = "CALIFORNIA", hjust = "left")+    
  annotate(geom = "point", x = 1998, y = 2955, colour = "#00AE9C", size = 3) + 
  annotate(geom = "text", x = 1998.3, y = 3500, label = "WASHINGTON", hjust = "left")+    
  annotate(geom = "point", x = 1998, y = 2250, colour = "#FF8F82", size = 3) + 
  annotate(geom = "text", x = 1998.3, y = 1900, label = "OREGON", hjust = "left")
```

```{r colorblind friendly - desaturated}

#Replication of code block above with a few changes: colors completely desaturated for accessibility, and background gray altered (using theme_minimal)
ggplot(purifiedhoney, aes(year, prodsimpler)) +
  geom_line(aes(group=state),
            color = "gray95") +
  geom_line(data = filter(purifiedhoney,
                           state == "OR"),
           color = "gray10") +
    geom_line(data = filter(purifiedhoney,
                           state == "WA"),
           color = "gray65") +
  
    geom_line(data = filter(purifiedhoney,
                           state == "CA"),
           color = "gray40") +
  scale_y_log10()+
  labs(title = "US Honey Production",
       subtitle = "1998-2012",
       y = "Thousands of gallons",
       x = "Year",
       caption = "99% of a bee colony is made up of female bees.")+  
  theme_minimal()+
  annotate(geom = "point", x = 1998, y = 37350, colour = "gray40", size = 3) + 
  annotate(geom = "text", x = 1998.3, y = 37350, label = "CALIFORNIA", hjust = "left")+    
  annotate(geom = "point", x = 1998, y = 2955, colour = "gray70", size = 3) + 
  annotate(geom = "text", x = 1998.3, y = 3500, label = "WASHINGTON", hjust = "left")+    
  annotate(geom = "point", x = 1998, y = 2250, colour = "gray10", size = 3) + 
  annotate(geom = "text", x = 1998.3, y = 1900, label = "OREGON", hjust = "left")
```

```{r color blind safe palette}

#Replication of code block above, with colors selected specifically to be safe with an audience that is colorblind
ggplot(purifiedhoney, aes(year, prodsimpler)) +
  geom_line(aes(group=state),
            color = "gray90") +
  geom_line(data = filter(purifiedhoney,
                           state == "OR"),
           color = "#00A078") +
    geom_line(data = filter(purifiedhoney,
                           state == "WA"),
           color = "#FC6426") +
  
    geom_line(data = filter(purifiedhoney,
                           state == "CA"),
           color = "#FFA12C") +
  scale_y_log10()+
  labs(title = "US Honey Production",
       subtitle = "1998-2012",
       y = "Thousands of gallons",
       x = "Year",
       caption = "Bees have an excellent sense of smell.")+    
  theme_minimal()+
  annotate(geom = "point", x = 1998, y = 37350, colour = "#FFA12C", size = 3) + 
  annotate(geom = "text", x = 1998.3, y = 37350, label = "CALIFORNIA", hjust = "left")+    
  annotate(geom = "point", x = 1998, y = 2955, colour = "#FC6426", size = 3) + 
  annotate(geom = "text", x = 1998.3, y = 3500, label = "WASHINGTON", hjust = "left")+    
  annotate(geom = "point", x = 1998, y = 2250, colour = "#00A078", size = 3) + 
  annotate(geom = "text", x = 1998.3, y = 1900, label = "OREGON", hjust = "left")

```

```{r join with census regions}
regional_honey_production <- left_join(purifiedhoney, census_regions) %>% 
  group_by(state, Region) %>% 
  summarise(totalprod = mean(totalprod)) %>% 
  ungroup() %>% 
  mutate(Region = as.factor(Region))

# Leaving this in case we need it
#         fct_reorder(Region,
#                            "Midwest",
#                            "West",
#                            "South",
#                            "Northeast"))
```

```{r bar plot showing average honey production, with color indicating region}
ggplot(regional_honey_production, aes(reorder(state, -totalprod), totalprod, fill = Region)) +
  geom_col(aes(group = Region)) +
  coord_flip() +
  labs(title = "Average Honey Production",
       subtitle = "Per state with color indicating region", 
       y = "Total production per gallon (thousands)",
       x = "")
```

Most honey production for the United States occurs in the Midwest and West. This is not surprising as most of the crop production for the country also occurs in these areas; bees would thrive in areas where there are high levels of crop production. The lowest production rate is in the northeast. 

```{r heatmap of average production by region}

premium_honey <- imported_honey_production %>%
  select(state, year)

# Data for heatmap
heat_dat <- full_join(premium_honey, regional_honey_production) %>%
  group_by(year, Region) %>% 
  mutate(totalprod = round(mean(totalprod)))

# Heatmap
ggplot(heat_dat, aes(year, Region, fill = totalprod)) +
  geom_raster(hjust = 0, vjust = 0) +
  scale_fill_viridis_c(option = "magma") +
  labs(title = "Average Honey Production by Region", 
       subtitles = "1998-2012",
       x = "",
       y = "Region")

```

```{r choice plot}

library(hexbin)
# On the bee theme, I'm gonna try something that looks like a honey comb.

# Ignore the following commented data:
# hex_dat <- full_join(premium_honey, regional_honey_production)

ggplot(imported_honey_production, aes(year, priceperlb)) +
  geom_hex(bins = 15) +
  scale_fill_viridis_c(guide = FALSE) +
  scale_x_continuous(breaks = NULL) +
  scale_y_continuous(breaks = NULL) +
  theme_minimal() +
  labs(title = "Honey Prices per Pound from 1998 to 2012",
       subtitle = "Per state",
       x = "Year",
       y = "Price per pound")

#Added title and subtitle based on my observations but could use some tweaking
#Deleted background grid lines and legend to provide more space

```